name: elmsln
type: php
docroot: domains
php_version: 7.2
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
disable_settings_management: true
additional_hostnames:
  - courses.elmsln
  - media.elmsln
  - online.elmsln
  - analytics.elmsln
  - studio.elmsln
  - interact.elmsln
  - blog.elmsln
  - comply.elmsln
  - discuss.elmsln
  - inbox.elmsln
  - people.elmsln
  - innovate.elmsln
  - grades.elmsln
  - hub.elmsln
  - data-courses.elmsln
  - data-media.elmsln
  - data-online.elmsln
  - data-studio.elmsln
  - data-interact.elmsln
  - data-blog.elmsln
  - data-comply.elmsln
  - data-discuss.elmsln
  - data-inbox.elmsln
  - data-people.elmsln
  - data-innovate.elmsln
  - data-grades.elmsln
  - data-hub.elmsln
  - data-lq.elmsln
provider: default
hooks:
  post-start:
    - exec: "sudo ln -s /var/www/html /var/www/elmsln"
    - exec: "sudo DEBIAN_FRONTEND=noninteractive apt-get -o Acquire::https::No-Cache=True -o Acquire::http::No-Cache=True update"
    - exec: "sudo DEBIAN_FRONTEND=noninteractive apt-get -y install software-properties-common"
    - exec: "curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -"
    - exec: "sudo DEBIAN_FRONTEND=noninteractive apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xF1656F24C74CD1D8"
    - exec: "sudo DEBIAN_FRONTEND=noninteractive apt-get -y update"
    - exec: "sudo DEBIAN_FRONTEND=noninteractive apt-get -y install dirmngr dialog apt-utils"
    - exec: "sudo bash /var/www/html/scripts/install/handsfree/ddev/handsfree-ddev.sh elmsln ln elmsln.ddev.site https admin@elmsln.dev yes ${DDEV_USER}"
    - exec: "sudo rm -rf /root/.composer && sudo cp -a /home/$DDEV_USER/.composer/. /root/.composer/"
    - exec: "sudo rm -rf /root/.drush && sudo cp -a /home/$DDEV_USER/.drush/. /root/.drush/"
    - exec: "sudo mkdir /root/.config"
    - exec: "sudo bash /var/www/html/scripts/install/handsfree/ddev/handsfree-ddev-restart.sh"
    - exec: "sudo service cron start"